### ISSUE TITLE
The result is a different color compared to the original repo.

### ISSUE THREAD

**Issue by toyxyz** [thecooltechguy/ComfyUI-MagicAnimate#1]
Compared to the original repo, the video generated by comfyui is less saturated.

Original repo

https://github.com/thecooltechguy/ComfyUI-MagicAnimate/assets/8006000/c082a471-e39a-4d8e-91ad-daff389176b2

ComfyUI

https://github.com/thecooltechguy/ComfyUI-MagicAnimate/assets/8006000/cd0a20a9-30d1-4253-b69e-80e1d093913f

**Comment by inferno46n2** [comment]
Temporary fix for this is using ColorMatch node

**Comment by PaulCollingwood** [comment]
> Temporary fix for this is using ColorMatch node

is that a reference to a setting I can tweak or using some nodes to restore the color from the original input image? 

great work thecooltechguy.

**Comment by p80ric** [comment]
Love it please fix it :)

**Comment by DedBazirovanniy** [comment]
> Temporary fix for this is using ColorMatch node

Can you tell me which addon this node is from?

**Comment by mingqizhang** [comment]
> worked out colormatch. Yeah, that helps a bit.
Could you tell me which plug-in have the ColorMatch node?

**Comment by PaulCollingwood** [comment]
KJNodes but it does not help with the distortion

**Comment by DedBazirovanniy** [comment]
> KJNodes but it does not help with the distortion

Thanks

**Comment by mingqizhang** [comment]
I modify the code and fix this problem

**Comment by toyxyz** [comment]
> I modify the code and fix this problem

Nice! Can you tell me what part of the code you modified?

**Comment by PaulCollingwood** [comment]
or make a PR even! Sigh..

**Comment by thecooltechguy** [comment]
Thank you so much @mingqizhang for the PR!! Closing this issue
