### ISSUE TITLE
The results are too white

### ISSUE THREAD

**Issue by zark119** [thecooltechguy/ComfyUI-MagicAnimate#10]
The results are similar to your example. It looks covering with a semi transparent white layer. The official examples have correct color.
From your nodes:
![image](https://github.com/thecooltechguy/ComfyUI-MagicAnimate/assets/113127641/dbcecd6e-f684-4be1-9d03-11f6501224d6)

Official examples:
![image](https://github.com/thecooltechguy/ComfyUI-MagicAnimate/assets/113127641/5a7bf87e-e433-490e-8d40-5f4eceefcfe1)

**Comment by thecooltechguy** [comment]
Hi! This has now been fixed: https://github.com/thecooltechguy/ComfyUI-MagicAnimate/pull/11
